get_maps:
  target:
    entity:
      integration: roborock
      domain: vacuum
set_vacuum_goto_position:
  target:
    entity:
      integration: roborock
      domain: vacuum
  fields:
    x:
      example: 27500
      required: true
      selector:
        text:
          type: number
    y:
      example: 32000
      required: true
      selector:
        text:
          type: number
get_vacuum_current_position:
  target:
    entity:
      integration: roborock
      domain: vacuum
clean_rooms:
  target:
    entity:
      integration: roborock
      domain: vacuum
  fields:
    rooms:
      example: ["Living Room", "Kitchen"]
      required: true
      selector:
        select:
          multiple: true
          options: []
